#!/usr/bin/env python3
"""
mkrom.py -- turn an assembled bootloader binary into a self-contained bootrom.vhd
            whose ROM contents are a VHDL CONSTANT (no .mif, no RAM inference).

Use this instead of mkmif.py if the .mif-based ROM comes up empty (Quartus only
honours ram_init_file for inferred block RAM, which needs a registered read; a
combinational ROM silently ignores the init file). A constant array always
synthesises with its values, implemented in logic.

    nasm -f bin bootldr.asm -o bootldr.bin
    python mkrom.py bootldr.bin bootrom.vhd 256
"""

import sys

HEADER = '''--------------------------------------------------------------------------------
-- bootrom.vhd  --  reset-time boot overlay (ROM contents baked in as a CONSTANT)
--
-- Generated by mkrom.py from bootldr.bin. The bootloader is overlaid on
-- 0xFFF00..0xFFFFF while ROM_EN='1' (set at reset); OUT 0xE2 bit0 clears ROM_EN.
-- The ROM is a combinational constant array, so its contents do NOT depend on
-- Quartus RAM inference or an external .mif.
--------------------------------------------------------------------------------

LIBRARY IEEE;
USE  IEEE.STD_LOGIC_1164.all;
USE  IEEE.STD_LOGIC_ARITH.all;
USE  IEEE.STD_LOGIC_UNSIGNED.all;

ENTITY bootrom IS
  PORT(
        CLK      : IN    std_logic;
        RESET    : IN    std_logic;
        MEM_ADDR : IN    std_logic_vector(7 DOWNTO 0);
        ROM_DATA : OUT   std_logic_vector(7 DOWNTO 0);
        ROM_EN   : OUT   std_logic;
        IO_ADDR  : IN    std_logic_vector(15 DOWNTO 0);
        IO_WR    : IN    std_logic;
        DATAIN   : IN    std_logic_vector(7 DOWNTO 0) );
END bootrom;

ARCHITECTURE behavior OF bootrom IS
  TYPE rom_t IS ARRAY (0 TO {depth_minus_1}) OF std_logic_vector(7 DOWNTO 0);
  CONSTANT rom : rom_t := (
{rom_body}
  );
  SIGNAL rom_en_i : std_logic := '1';
  SIGNAL wr_prev  : std_logic := '1';
BEGIN
  ROM_EN   <= rom_en_i;
  ROM_DATA <= rom(conv_integer(MEM_ADDR));

  PROCESS (CLK)
  BEGIN
    IF rising_edge(CLK) THEN
      IF RESET = '1' THEN
        rom_en_i <= '1';
        wr_prev  <= '1';
      ELSE
        wr_prev <= IO_WR;
        IF (wr_prev = '0' AND IO_WR = '1' AND IO_ADDR = x"00E2") THEN
          IF DATAIN(0) = '1' THEN
            rom_en_i <= '0';
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS;
END;
'''

def main():
    if len(sys.argv) != 4:
        sys.exit("usage: mkrom.py <in.bin> <out.vhd> <depth>")
    inp, outp, depth = sys.argv[1], sys.argv[2], int(sys.argv[3])

    data = bytearray(open(inp, "rb").read())
    if len(data) > depth:
        data = data[:depth]
    data += bytes([0x90] * (depth - len(data)))   # pad with NOP

    lines = []
    for addr in range(depth):
        lines.append(f'    {addr} => x"{data[addr]:02X}"')
    rom_body = ",\n".join(lines)

    out = HEADER.format(depth_minus_1=depth - 1, rom_body=rom_body)
    with open(outp, "w") as f:
        f.write(out)
    print(f"wrote {outp}: {depth}-byte constant ROM")

if __name__ == "__main__":
    main()
